Updated dependency versions
ghga-de/experiment-repository-template pull request #7
Opened 2023-01-19 16:43 UTC by mephenor

2023-01-23 11:39 UTC, KerstenBreuer requested changes

2023-01-23 11:39 UTC, KerstenBreuer commented on requirements.txt
> +testcontainers[kafka,mongo,postgresql]==3.7.1
```suggestion
testcontainers[kafka,mongo,postgresql]==3.4.2
```

2023-01-23 12:40 UTC, KerstenBreuer requested changes

2023-01-23 12:40 UTC, KerstenBreuer commented on requirements.txt
> +testcontainers[kafka,mongo,postgresql]==3.4.2
```suggestion
testcontainers[kafka,mongo,postgresql]==3.4.1
```

2023-01-24 11:53 UTC, MoritzHahn1337 approved these changes

2023-01-24 12:29 UTC, KerstenBreuer approved these changes

2023-01-24 12:30 UTC, merged